src/models/grafico_espessura_dinamica.py
import os
from datetime import datetime

import matplotlib.pyplot as plt

from src.models.grafico_reflection_loss import GraficoReflectionLoss


class GraficoEspessuraDinamica(GraficoReflectionLoss):
    def plotar_grafico(
        self,
        espessura_amostra: float = 1.0,
        inicio_slider: float = 1.0,
        fim_slider: float = 10.0,
    ):
        conteudo_arquivo_txt = self._ler_dados_arquivo_txt()

        frequencias_plotagem, s11_v = self._calcular_rl(
            conteudo_arquivo_txt=conteudo_arquivo_txt,
            espessura_amostra=espessura_amostra,
        )

        print("Gerando gráfico de perda por reflexão com espessura dinâmica.")
        fig = plt.figure(figsize=(10, 5))
        plt.plot(frequencias_plotagem, s11_v, label=str(espessura_amostra))
        plt.legend(title="Espessura (mm)")
        plt.xlabel(f"Frequência ({self._unidade_frequencia})")
        plt.ylabel("Perda por Reflexão (dB)")
        plt.title(f"Arquivo: {self._nome_arquivo_csv}")

        nome_arquivo_imagem = (
            f"rl_epessura_dinamica_{self._identificador_arquivo}.png"
        )

        caminho_imagem = f"{os.getenv("STATIC_FOLDER_PATH")}/images/graficos_gerados/{nome_arquivo_imagem}"
        fig.savefig(caminho_imagem)
        print("Gráfico de espessura dinâmica gerado com sucesso.")

        dados_plotagem = {
            "caminho_imagem": caminho_imagem,
            "nome_arquivo_imagem": nome_arquivo_imagem,
            "espessura_amostra": espessura_amostra,
            "timestamp": datetime.now().timestamp(),  # usado para cache busting
            "inicio_slider": inicio_slider,
            "fim_slider": fim_slider,
        }
        return dados_plotagem

    def baixar_dados_grafico(
        self,
        espessura_amostra: float = 1.0,
    ):
        print(
            "Gerando arquivo com dados do gráfico de espessura dinâmica para download."
        )
        pasta_arquivo = f"{os.getenv("STATIC_FOLDER_PATH")}/files/saidas/saidas_{self._identificador_arquivo}"
        os.makedirs(pasta_arquivo, exist_ok=True)

        caminho_arquivo = (
            f"{pasta_arquivo}/mm_{round(espessura_amostra, 2)}mm.txt"
        )

        with open(
            caminho_arquivo,
            "w",
            encoding="utf-8",
        ) as arquivo_dados_grafico:
            # Cabeçalho do arquivo enviado para download
            arquivo_dados_grafico.write(
                f"Frequência({self._unidade_frequencia}) RL(dB)"
            )

            frequencias_plotagem, s11_v = self._calcular_rl(
                conteudo_arquivo_txt=self._ler_dados_arquivo_txt(),
                espessura_amostra=espessura_amostra,
            )

            for frequencia, rl in zip(frequencias_plotagem, s11_v):
                arquivo_dados_grafico.write(f"\n{frequencia:.6f}\t{rl:.2f}")
        print(
            "Arquivo com dados do gráfico de espessura dinâmica gerado com sucesso."
        )
        return caminho_arquivo

src/models/grafico_espessura_fixa.py
import os

import matplotlib.pyplot as plt

from src.models.grafico_reflection_loss import GraficoReflectionLoss


class GraficoEspessuraFixa(GraficoReflectionLoss):
    def __init__(
        self,
        nome_arquivo_csv: str,
        caminho_arquivo_txt: str,
        unidade_frequencia: str,
        identificador_arquivo: str,
        espessura_amostra: float,
    ):
        super().__init__(
            nome_arquivo_csv=nome_arquivo_csv,
            caminho_arquivo_txt=caminho_arquivo_txt,
            unidade_frequencia=unidade_frequencia,
            identificador_arquivo=identificador_arquivo,
        )
        self._espessura_amostra = espessura_amostra

    def plotar_grafico(self) -> dict:
        conteudo_arquivo_txt = self._ler_dados_arquivo_txt()

        frequencias_plotagem, s11_v = self._calcular_rl(
            conteudo_arquivo_txt=conteudo_arquivo_txt,
            espessura_amostra=self._espessura_amostra,
        )

        print("Gerando gráfico de perda por reflexão com espessura fixa.")
        fig = plt.figure(figsize=(10, 5))
        plt.plot(
            frequencias_plotagem, s11_v, label=str(self._espessura_amostra)
        )  # Dados para serem plotados
        plt.legend(title="Espessura (mm)")
        plt.xlabel(f"Frequência ({self._unidade_frequencia})")
        plt.ylabel("Perda por Reflexão (dB)")
        plt.title(f"Arquivo: {self._nome_arquivo_csv}")

        nome_arquivo_imagem = (
            f"rl_epessura_fixa_{self._identificador_arquivo}.png"
        )

        caminho_imagem = f"{os.getenv("STATIC_FOLDER_PATH")}/images/graficos_gerados/{nome_arquivo_imagem}"
        fig.savefig(caminho_imagem)
        print("Gráfico de espessura fixa gerado com sucesso.")

        dados_plotagem = {
            "caminho_imagem": caminho_imagem,
            "nome_arquivo_imagem": nome_arquivo_imagem,
        }
        return dados_plotagem

    def baixar_dados_grafico(self):
        print(
            "Gerando arquivo com dados do gráfico de espessura fixa para download."
        )
        pasta_arquivo = f"{os.getenv("STATIC_FOLDER_PATH")}/files/saidas/saidas_{self._identificador_arquivo}"
        os.makedirs(pasta_arquivo, exist_ok=True)

        caminho_arquivo = (
            f"{pasta_arquivo}/mm_{round(self._espessura_amostra, 2)}mm.txt"
        )
        with open(
            caminho_arquivo,
            "w",
            encoding="utf-8",
        ) as arquivo_dados_grafico:
            # Cabeçalho do arquivo enviado para download
            arquivo_dados_grafico.write(
                f"Frequência({self._unidade_frequencia}) RL(dB)"
            )

            frequencias_plotagem, s11_v = self._calcular_rl(
                conteudo_arquivo_txt=self._ler_dados_arquivo_txt(),
                espessura_amostra=self._espessura_amostra,
            )

            for frequencia, rl in zip(frequencias_plotagem, s11_v):
                arquivo_dados_grafico.write(f"\n{frequencia:.6f}\t{rl:.2f}")

        print(
            "Arquivo com dados do gráfico de espessura fixa gerado com sucesso."
        )
        return caminho_arquivo

src/models/grafico_espessura_variavel.py
import os
from datetime import datetime

import matplotlib.pyplot as plt
import numpy as np

from src.models.grafico_reflection_loss import GraficoReflectionLoss


class GraficoEspessuraVariavel(GraficoReflectionLoss):
    def plotar_grafico(
        self, inicio: float = 1.0, fim: float = 10.0, passo: float = 1.0
    ):
        conteudo_arquivo_txt = self._ler_dados_arquivo_txt()

        print("Gerando gráfico de perda por reflexão com espessura variável.")
        fig = plt.figure(figsize=(10, 5))

        menor_rl_global = float("inf")
        espessura_menor_rl = float("inf")

        for espessura in np.arange(inicio, fim, passo):
            espessura = round(espessura, 3)

            frequencias_plotagem, s11_v = self._calcular_rl(
                conteudo_arquivo_txt=conteudo_arquivo_txt,
                espessura_amostra=espessura,
            )

            menor_rl_da_curva = min(s11_v)
            if menor_rl_da_curva < menor_rl_global:
                menor_rl_global = menor_rl_da_curva
                espessura_menor_rl = espessura

            # Dados para serem plotados em uma linha individual
            plt.plot(frequencias_plotagem, s11_v, label=str(espessura))

        # Plotando grafico final com todas as linhas
        plt.legend(title="Espessura (mm)")
        plt.xlabel(f"Frequência ({self._unidade_frequencia})")
        plt.ylabel("Perda por Reflexão (dB)")
        plt.title(f"Arquivo: {self._nome_arquivo_csv}")

        nome_arquivo_imagem = (
            f"rl_epessura_variavel_{self._identificador_arquivo}.png"
        )
        caminho_imagem = f"{os.getenv("STATIC_FOLDER_PATH")}/images/graficos_gerados/{nome_arquivo_imagem}"
        fig.savefig(caminho_imagem)
        print("Gráfico de espessura variável gerado com sucesso.")

        dados_plotagem = {
            "espessura_menor_rl": espessura_menor_rl,
            "caminho_imagem": caminho_imagem,
            "nome_arquivo_imagem": nome_arquivo_imagem,
            "timestamp": datetime.now().timestamp(),  # usado para cache busting
        }
        return dados_plotagem

    def baixar_dados_grafico(
        self,
        inicio: float = 1.0,
        fim: float = 10.0,
        passo: float = 1.0,
    ):
        print(
            "Gerando arquivo com dados do gráfico de espessura variável para download."
        )
        pasta_arquivos_saida = f"{os.getenv("STATIC_FOLDER_PATH")}/files/saidas/saidas_{self._identificador_arquivo}"
        os.makedirs(pasta_arquivos_saida, exist_ok=True)

        frequencias_agrupamento = (
            list()
        )  # armazena as frequencias (valores x) do gráfico para gerar arquivo único
        s11_v_agrupadas = []  # armazena todos os valores de RL do gráfico

        for espessura in np.arange(inicio, fim, passo):
            espessura = round(espessura, 3)
            # Criando arquivo individual para cada espessura
            with open(
                f"{pasta_arquivos_saida}/mm_{espessura}mm.txt",
                "w",
                encoding="utf-8",
            ) as arquivo_grafico_individual:
                # Cabeçalho do arquivo enviado para download
                arquivo_grafico_individual.write(
                    f"Frequência({self._unidade_frequencia}) RL(dB)"
                )

                frequencias_plotagem, s11_v = self._calcular_rl(
                    conteudo_arquivo_txt=self._ler_dados_arquivo_txt(),
                    espessura_amostra=espessura,
                )

                # Salva dados para arquivo com todas as espessuras
                frequencias_agrupamento = frequencias_plotagem
                s11_v_agrupadas.append(s11_v)

                # Grava dados no arquivo individual
                for frequencia, rl in zip(frequencias_plotagem, s11_v):
                    arquivo_grafico_individual.write(
                        f"\n{frequencia:.6f}\t{rl:.2f}"
                    )

        dados_grafico_agrupado = [frequencias_agrupamento] + s11_v_agrupadas

        # Criando arquivo único com todas as espessuras
        with open(
            f"{pasta_arquivos_saida}/todos.txt",
            "w",
            encoding="utf-8",
        ) as arquivo_grafico_agrupado:
            for linha in zip(*dados_grafico_agrupado):
                valores = (float(valor) for valor in linha)
                arquivo_grafico_agrupado.write(
                    "  ".join(f"{v:.6f}" for v in valores) + "\n"
                )

        print(
            "Arquivo com dados do gráfico de espessura variável gerado com sucesso."
        )
        return pasta_arquivos_saida

src/models/grafico_mu_epsilon.py
import os

import matplotlib.pyplot as plt
import numpy as np

from src.interfaces.grafico import Grafico


class GraficoMuEpsilon(Grafico):
    def __init__(
        self,
        nome_arquivo_csv: str,
        caminho_arquivo_txt: str,
        unidade_frequencia: str,
        identificador_arquivo: str,
    ):
        self._nome_arquivo_csv = nome_arquivo_csv
        self._caminho_arquivo_txt = caminho_arquivo_txt
        self._unidade_frequencia = unidade_frequencia
        self._identificador_arquivo = identificador_arquivo

    def _ler_dados_arquivo_txt(self) -> tuple:
        print("Lendo dados do arquivo txt para plotar mu e epsilon.")
        try:
            dados = np.loadtxt(self._caminho_arquivo_txt)
        except Exception as e:
            print(f"Erro ao ler arquivo txt para plotar mu e epsilon: {e}")
            raise

        print("Extraindo dados de mu e epsilon")
        frequencia = dados[:, 0]
        epsilon = dados[:, 1]
        epsilon_prime = dados[:, 2]
        mu = dados[:, 3]
        mu_prime = dados[:, 4]

        return frequencia, epsilon, epsilon_prime, mu, mu_prime

    def plotar_grafico(self):
        frequencia, epsilon, epsilon_prime, mu, mu_prime = (
            self._ler_dados_arquivo_txt()
        )

        print("Iniciando plotagem do gráfico de permissividade elétrica")
        fig = plt.figure(figsize=(10, 5))
        ax = fig.add_subplot(1, 2, 1)
        plt.plot(frequencia, epsilon, label="\u03b5'")
        plt.plot(frequencia, epsilon_prime, label="\u03b5''")
        plt.xlabel(f"Frequência ({self._unidade_frequencia})")
        plt.ylabel("Permissividade Elétrica Relativa (\u03b5\u1d63)")
        plt.title(
            f"Arquivo: {self._nome_arquivo_csv}\nGráfico \u03b5' vs. \u03b5'' em função da Frequência"
        )
        plt.legend()
        plt.grid(True)
        print("Plotagem do gráfio de permissividade elétrica finalizada")

        print("Iniciando plotagem do gráfico de permeabilidade magnética")
        ax = fig.add_subplot(1, 2, 2)
        plt.plot(frequencia, mu, label="\u00b5'")
        plt.plot(frequencia, mu_prime, label="\u00b5''")
        plt.xlabel(f"Frequência ({self._unidade_frequencia})")
        plt.ylabel("Permeabilidade Magnética Relativa (\u00b5\u1d63)")
        plt.title(
            f"Arquivo: {self._nome_arquivo_csv}\nGráfico \u00b5' vs. \u00b5'' em função da Frequência"
        )
        plt.legend()
        plt.grid(True)
        print("Plotagem do gráfico de permeabilidade magnética finalizada")

        nome_arquivo_imagem = f"mi_epsilon_{self._identificador_arquivo}.png"
        caminho_imagem = f"{os.getenv("STATIC_FOLDER_PATH")}/images/graficos_gerados/{nome_arquivo_imagem}"
        fig.savefig(caminho_imagem)

        dados_plotagem = {
            "nome_arquivo_imagem": nome_arquivo_imagem,
        }

        return dados_plotagem

    def baixar_dados_grafico(self):
        print(
            "Gerando arquivo com dados do gráfico de permeabilidade magnética e permissividade elétrica para download."
        )
        pasta_arquivo = f"{os.getenv("STATIC_FOLDER_PATH")}/files/saidas/saidas_{self._identificador_arquivo}"
        os.makedirs(pasta_arquivo, exist_ok=True)

        caminho_arquivo = (
            f"{pasta_arquivo}/mu_epsilon_{self._identificador_arquivo}.txt"
        )

        with open(
            self._caminho_arquivo_txt, "r", encoding="utf-8"
        ) as arquivo_txt_original:
            linhas = arquivo_txt_original.readlines()

        with open(
            caminho_arquivo, "w", encoding="utf-8"
        ) as arquivo_dados_grafico:
            # Cabeçalho do arquivo enviado para download
            arquivo_dados_grafico.write(
                f"F({self._unidade_frequencia})\t    e'\t\t    e''\t\t    mu'\t\t    mu''\n"
            )
            arquivo_dados_grafico.writelines(linhas)

        print(
            "Arquivo com dados do gráfico de permeabilidade magnética e permissividade elétrica gerado com sucesso."
        )
        return caminho_arquivo

src/controllers/baixar_arquivo_exemplo.py
import os

from flask import Blueprint, send_file

baixar_arquivo_exemplo_bp = Blueprint(
    "baixar_arquivo_exemplo", __name__, url_prefix="/arquivo"
)


@baixar_arquivo_exemplo_bp.route(
    "/baixar-arquivo-exemplo", methods=["GET", "POST"]
)
def baixar_arquivo_exemplo():
    print("Retornando arquivo de exemplo.")
    return send_file(
        f"{os.getenv("STATIC_FOLDER_PATH")}/files/exemplos/exemplo.csv",
        as_attachment=True,
        download_name="exemplo.csv",
    )

src/controllers/home.py
from flask import Blueprint, render_template

home_bp = Blueprint("home", __name__)


@home_bp.route("/", methods=["GET", "POST"])
def home():
    return render_template("home.html")

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Analisador de Amostras VNA{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <header>
        <b>Analisador de Amostras VNA |</b>
        <a href="/" class="btn-link">Home</a>
        <a href="/enviar-arquivo" class="btn-link">1 camada</a>
        <div class="images">
            <img src="{{ url_for('static', filename='images/logoINPE.png') }}" alt="Logotipo do INPE">
            <img src="{{ url_for('static', filename='images/logoFATEC.png') }}" alt="Logotipo da FATEC Taubate">
        </div>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <p>Agradecimento: PIBIC/CNPq Processo Nº 101700/2024-5 - Instituto Nacional de Pesquisas Espaciais</p>
        <p>Todos os direitos reservados &copy;</p>
    </footer>
</body>
</html>

src/templates/grafico_espessura_dinamica.html
{% extends "base.html" %}

{% block title %}Gráfico - VNA{% endblock %}

{% block content %}
    <form action="/informacoes" method="post">
        <button type="submit">Retornar ao menu</button>
    </form>
    <div id="grafico" class="grafico-container">
        <img src="{{ url_for('static', filename='images/graficos_gerados/' + nome_arquivo_imagem) }}?t={{ timestamp }}">
    </div>

    <div class="controles-grafico">
        <form action="/grafico/rl-espessura-dinamica/baixar-dados" method="post">
            <button type="submit">Baixar dados do gráfico</button>
        </form>

        <form action="/grafico/rl-espessura-dinamica#grafico" method="post">
            <div class="campo-input">
                Espessura mínima em mm: <input type="number" name="inicio_slider" step="any" value="{{ inicio_slider }}" required="true">
            </div>

            <div class="campo-input">
                Espessura máxima em mm: <input type="number" name="fim_slider" step="any" value="{{ fim_slider }}" required="true">
            </div>

            <div class="campo slider-container">
                <input type="range" id="espessura_amostra" name="espessura_amostra" min="{{ inicio_slider }}" max="{{ fim_slider }}" step="0.001" value="{{ espessura_amostra }}" onchange=submit()>
                <span class="slider-text">Espessura: {{ espessura_amostra }} mm</span>
            </div>
        </form>
    </div>
{% endblock %}

src/templates/grafico_espessura_fixa.html
{% extends "base.html" %}

{% block title %}Gráfico - VNA{% endblock %}

{% block content %}
    <form action="/informacoes" method="post">
        <button type="submit">Retornar ao menu</button>
    </form>
    <div class="grafico-container">
        <img src="{{ url_for('static', filename='images/graficos_gerados/' + nome_arquivo_imagem) }}">
    </div>

    <div class="controles-grafico">
        <form action="/grafico/rl-espessura-fixa/baixar-dados" method="post">
            <button type="submit">Baixar dados do gráfico</button>
        </form>
    </div>
{% endblock %}

src/templates/grafico_espessura_variavel.html
{% extends "base.html" %}

{% block title %}Gráfico - VNA{% endblock %}

{% block content %}
    <form action="/informacoes" method="post">
        <button type="submit">Retornar ao menu</button>
    </form>
    <div class="grafico-container">
        <img src="{{ url_for('static', filename='images/graficos_gerados/' + nome_arquivo_imagem) }}">
    </div>
    <div class="controles-grafico">
        <h3>Curva de menor RL: Espessura {{ espessura_menor_rl }} mm</h3>
        <form action="/grafico/rl-espessura-variavel/baixar-dados" method="post">
            <button type="submit">Baixar dados do gráfico</button>
        </form>
    </div>
{% endblock %}

src/templates/grafico_mi_epsilon.html
{% extends "base.html" %}

{% block title %}Gráfico - VNA{% endblock %}

{% block content %}
<form action="/informacoes" method="post">
<button type="submit">Retornar ao menu</button>
</form>

<div class="grafico-container">
    <img src="{{ url_for('static', filename='images/graficos_gerados/' + nome_arquivo_imagem) }}">
</div>
{% endblock %}

src/templates/grafico_mu_epsilon.html
{% extends "base.html" %}

{% block title %}Gráfico - VNA{% endblock %}

{% block content %}
    <form action="/informacoes" method="post">
    <button type="submit">Retornar ao menu</button>
    </form>

    <div class="grafico-container">
        <img src="{{ url_for('static', filename='images/graficos_gerados/' + nome_arquivo_imagem) }}">
    </div>

    <div class="controles-grafico">
        <form action="/grafico/mu-epsilon/baixar-dados" method="post">
            <button type="submit">Baixar dados do gráfico</button>
        </form>
    </div>
{% endblock %}

src/templates/home.html
{% extends "base.html" %}

{% block title %}Home - Analisador de Amostras VNA{% endblock %}

{% block content %}
    <div class="apresentacao-ferramenta">
        <h1>Analisador de Amostras VNA</h1>
        <h2 class="texto-cinza">Selecione a opção correspondente à sua amostra:</h2>
    </div>

    <div class="links-container">
        <a href="/enviar-arquivo" class="link-home">Análise com 1 camada</a>
    </div>

    <div class="instrucoes-home">
        <h3>Verifique se o seu arquivo está na formatação correta:</h3>
        <p><b>1. </b>Formato .csv</p>
        <p><b>2. </b>Deve possuir 1616 linhas (incluso cabeçalho)</p>
        <p><b>3. </b>Cabeçalho como apresentado no exemplo abaixo</p>
        <img src="{{ url_for('static', filename='images/inicial.png') }}" alt="Imagem de exemplo">
    </div>
{% endblock %}

src/templates/tela_de_envio_de_arquivo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arquivo 1 camada</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body style="background-color: #FAFAFA;">
    <header>
        <b>Analisador de Amostras VNA |</b>
        <a href="/" class="btn">Home</a>
        <a href="/arquivoumacamada" class="btn">1 camada</a>
        <a href="/primeiroarquivoduo" class="btn">2 camadas</a>
        <a href="/primeiroarquivo" class="btn">3 camadas</a>
        <a href="/arquivocoaxial" class="btn">Coaxial</a>
        <a href="/gerarxml" class="btn">Gerar XML</a>
        <div class="images">
            <img src="{{ url_for('static', filename='images/logoINPE.png') }}" alt="Logotipo do INPE">
            <img src="{{ url_for('static', filename='images/logoFATEC.png') }}" alt="Logotipo da FATEC Taubate">
        </div>
    </header>
    <h2><b>Para começar a análise siga este passo:</b></h2>
    <h3>Qual é o arquivo .csv da sua amostra analisada no VNA?</h3>

    <form method='POST' enctype='multipart/form-data'>
        {{form.hidden_tag()}}
        {{form.file()}}
        {{form.submit()}}
    </form>

    <img src="{{ url_for('static', filename='images/simples.PNG') }}" alt="Descrição da Imagem"  width="640" height="360">
    <footer>
        <p>Agradecimento: PIBIC/CNPq processo nº 101700/2024-5 - Instituto Nacional de Pesquisas Espaciais</p>
        <p>Todos os direitos reservados</p>
    </footer>
</body>
</html>

src/templates/tela_de_erro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
    <header>
        <b>Analisador de Amostras VNA |</b>
        <a href="/" class="btn">Home</a>
        <a href="/arquivoumacamada" class="btn">1 camada</a>
        <a href="/primeiroarquivoduo" class="btn">2 camadas</a>
        <a href="/primeiroarquivo" class="btn">3 camadas</a>
        <a href="/arquivocoaxial" class="btn">Coaxial</a>
        <a href="/gerarxml" class="btn">Gerar XML</a>
        <div class="images">
            <img src="{{ url_for('static', filename='images/logoINPE.png') }}" alt="Logotipo do INPE">
            <img src="{{ url_for('static', filename='images/logoFATEC.png') }}" alt="Logotipo da FATEC Taubate">
        </div>
    </header>

    <div class="primeiro-centralizado">
        <h1>Analisador de Amostras VNA</h1>
        <h2>Ocorreu um erro ao processar seu arquivo</h2>
        <h2>Por favor, verifique se ele está na formatação correta:</h2>
        <h3><b>1. </b>Formato .csv</h3>
        <h3><b>2. </b>Deve possuir 1616 linhas (incluso cabeçalho)</h3>
        <h3><b>3. </b>Cabeçalho como apresentado no exemplo abaixo</h3>
        <img src="{{ url_for('static', filename='images/inicial.png') }}" alt="Imagem de exemplo">
    </div>

    <footer>
        <p>Agradecimento: PIBIC/CNPq processo nº 101700/2024-5 - Instituto Nacional de Pesquisas Espaciais</p>
        <p>Todos os direitos reservados</p>
    </footer>

</body>
</html>

src/templates/tela_envio_de_arquivo.html
{% extends "base.html" %}

{% block title %}Enviar Arquivo - VNA{% endblock %}

{% block content %}

    <div class="instrucoes-home">
        <h2>Selecione o arquivo CSV da amostra analisada no VNA</h2>
        
        <img src="{{ url_for('static', filename='images/simples.png') }}" alt="Descrição da Imagem"  width="640" height="360">

        <form method='POST' enctype='multipart/form-data'>
            {{form.hidden_tag()}}
            {{form.file()}}
            {{form.submit()}}
        </form>

        <h4>
            Para baixar o arquivo de exemplo,
            <a href="{{ url_for('baixar_arquivo_exemplo.baixar_arquivo_exemplo') }}" class="link-download">
                clique aqui
            </a>
        </h4>
    </div>
{% endblock %}

src/templates/tela_erro.html
{% extends "base.html" %}

{% block title %}Home - Analisador de Amostras VNA{% endblock %}

{% block content %}
    <div class="apresentacao-ferramenta">
        <h1>Analisador de Amostras VNA</h1>
        <h2>Ocorreu um erro ao processar seu arquivo</h2>
        <h2>Por favor, verifique se ele está na formatação correta:</h2>
        <h3><b>1. </b>Formato .csv</h3>
        <h3><b>2. </b>Deve possuir 1616 linhas (incluso cabeçalho)</h3>
        <h3><b>3. </b>Cabeçalho como apresentado no exemplo abaixo</h3>
        <img src="{{ url_for('static', filename='images/inicial.png') }}" alt="Imagem de exemplo">
    </div>
{% endblock %}